services:
  mongo:
    image: mongo:8.0.6
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo-config-data:/data/configdb
      - mongo-db-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - "9500:9500"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      PORT: 9500
  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    command: server --address ":9000" --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: graphoenix
      MINIO_ROOT_PASSWORD: graphoenix
      MINIO_SERVER_URL: "http://localhost:9000"
      MINIO_STORAGE_USE_HTTPS: "false"
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  create-bucket:
    image: minio/mc:RELEASE.2025-03-12T17-29-24Z
    entrypoint: sh -c "mc config host add minio http://minio:9000 graphoenix graphoenix && mc mb minio/graphoenix"
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: "graphoenix"
      MINIO_SECRET_KEY: "graphoenix"
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: pg-root
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./bootstrap/pg:/docker-entrypoint-initdb.d:z
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    command: ["start-dev", "--import-realm"]
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./bootstrap/keycloak:/opt/keycloak/data/import
    ports:
      - "8090:8080"
  reverse-proxy:
    image: nginx:1.29.0-alpine
    ports:
      - "10000:10000"
    volumes:
      - ./bootstrap/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  mongo-config-data:
  mongo-db-data:
  minio-data:
  postgres-data:
