quarkus:
  http:
    port:
      8080
  mongodb:
    database: nx-cloud-ce
  smallrye-openapi:
    security-scheme: api-key
    api-key-parameter-in: header
    api-key-parameter-name: authorization

nx-server:
  application-url: http://localhost:8080
  client-bundle-version: 2401.03.1
  client-bundle-path: static/client-bundle.gz
  storage:
    s3:
      endpoint: http://localhost:9000
      region: us-east-1
      access-key-id: nx-cloud-ce
      secret-access-key: nx-cloud-ce
      bucket: nx-cloud-ce
      force-path-style: true

"%dev":
  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017
