apiVersion: v2
name: nx-cloud-ce
description: Nx Cloud Community Edition Helm Chart
type: application
version: "0.2.1"
appVersion: "v0.2.1"
keywords:
  - nx-cloud-ce
home: https://github.com/clementguillot/nx-cloud-ce
maintainers:
  - name: clementguillot
    email: clement1.guillot@gmail.com
sources:
  - https://github.com/clementguillot/nx-cloud-ce
dependencies:
  - name: mongodb
    version: 15.1.4
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: nginx
    version: 16.0.4
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
