apiVersion: v2
name: graphoenix
description: Graphoenix Helm Chart
type: application
version: "0.6.1"
appVersion: "v0.6.0"
keywords:
  - graphoenix
  - nx
  - cloud
home: https://github.com/clementguillot/graphoenix
maintainers:
  - name: clementguillot
    email: clement1.guillot@gmail.com
sources:
  - https://github.com/clementguillot/graphoenix
dependencies:
  - name: minio
    version: 14.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: mongodb
    version: 16.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: nginx
    version: 18.3.6
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
