apiVersion: v2
name: graphoenix
description: Graphoenix Helm Chart
type: application
version: "0.6.4"
appVersion: "v0.6.4"
keywords:
  - graphoenix
  - nx
  - cloud
home: https://github.com/clementguillot/graphoenix
maintainers:
  - name: clementguillot
    email: clement1.guillot@gmail.com
sources:
  - https://github.com/clementguillot/graphoenix
dependencies:
  - name: minio
    version: 15.0.7
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: mongodb
    version: 16.4.12
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: nginx
    version: 19.0.3
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
