apiVersion: v2
name: nx-cloud-ce
description: Nx Cloud Community Edition Helm Chart
type: application
version: "0.5.0"
appVersion: "v0.5.0"
keywords:
  - nx-cloud-ce
home: https://github.com/clementguillot/nx-cloud-ce
maintainers:
  - name: clementguillot
    email: clement1.guillot@gmail.com
sources:
  - https://github.com/clementguillot/nx-cloud-ce
dependencies:
  - name: minio
    version: 14.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: mongodb
    version: 16.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: nginx
    version: 18.2.4
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
