apiVersion: v2
name: graphoenix
description: Graphoenix Helm Chart
type: application
version: "0.7.1"
appVersion: "v0.7.1"
keywords:
  - graphoenix
  - nx
  - cloud
home: https://github.com/clementguillot/graphoenix
maintainers:
  - name: clementguillot
    email: clement1.guillot@gmail.com
sources:
  - https://github.com/clementguillot/graphoenix
dependencies:
  - name: minio
    version: 16.0.10
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: mongodb
    version: 16.5.13
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: nginx
    version: 20.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
