{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ template "graphoenix.fullname" . }}-nginx
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "graphoenix.labels" (dict "context" . "component" .Values.server.name "name" "nginx") | nindent 4 }}

data:
  nginx-server-block.conf: |-
    upstream server {
      server {{ template "graphoenix.server.fullname" . }}:{{ template "graphoenix.server.port". }};
    }

    server {
      listen {{ .Values.nginx.containerPorts.http }};

      location = / {
        auth_basic off;
      }

      {{- if .Values.nginx.extraServerBlockConfiguration }}
      {{ .Values.nginx.extraServerBlockConfiguration | nindent 6 }}
      {{- end }}

      location ^~ /nx-cloud/private {
        return 404;
      }

      location ^~ /nx-cloud {
        proxy_pass http://server;
      }
    }
{{- end }}
