quarkus:
  http:
    port: 8080
    root-path: "/nx-cloud"
  liquibase-mongodb:
    change-log: db/change-log.yaml
    migrate-at-start: true
  mongodb:
    database: nx-cloud-ce
  smallrye-openapi:
    security-scheme: api-key
    api-key-parameter-in: header
    api-key-parameter-name: authorization
  azure:
    app:
      configuration:
        enabled: false

nx-server:
  configuration:
    client-bundle-version: 2409.26.3.hotfix17
    client-bundle-path: nx-cloud/static/client-bundle

"%dev":
  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017
  nx-server:
    configuration:
      application-url: http://localhost:8080
    storage:
      type: s3
      s3:
        endpoint: http://localhost:9000
        region: us-east-1
        access-key-id: nx-cloud-ce
        secret-access-key: nx-cloud-ce
        bucket: nx-cloud-ce
        force-path-style: true
