name: 'Setup Tools'
description: 'Setup of common build tools and environment variables.'

runs:
  using: 'composite'
  steps:
    - uses: graalvm/setup-graalvm@4a200f28cd70d1940b5e33bd00830b7dc71a7e2b # v1.2.6
      with:
        java-version: '21.0.2'
        distribution: 'graalvm-community'

    - name: Set up Helm
      uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
      with:
        version: v3.14.4

    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        version: 9

    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: 20
        cache: 'pnpm'

    - run: pnpm install --frozen-lockfile
      shell: bash

    - uses: nrwl/nx-set-shas@be2a36618456ad6f3abf921eb24900817da1af6b # v4.1.1
