name: 'Setup Tools'
description: 'Setup of common build tools and environment variables.'

runs:
  using: 'composite'
  steps:
    - uses: graalvm/setup-graalvm@2f25c0caae5b220866f732832d5e3e29ff493338 # v1.2.1
      with:
        java-version: '21.0.2'
        distribution: 'graalvm-community'

    - name: Set up Helm
      uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
      with:
        version: v3.14.4

    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        version: 9

    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 #v4.0.2
      with:
        node-version: 20
        cache: 'pnpm'

    - run: pnpm install --frozen-lockfile
      shell: bash

    - uses: nrwl/nx-set-shas@76907e7e5d3cd17ddb5e2b123389f054bffcdd03 # v4.0.4
