name: 'Setup Tools'
description: 'Setup of common build tools and environment variables.'

runs:
  using: 'composite'
  steps:
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21.0.2'
        distribution: 'graalvm-community'

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - run: npm ci
      shell: bash

    - uses: nrwl/nx-set-shas@v4
