name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup build tools
        uses: ./.github/actions/setup-tools

      - name: Run Build for affected projects
        run: pnpm exec nx affected -t build
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  build-oci-images:
    needs:
      - build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup build tools
        uses: ./.github/actions/setup-tools

      - name: Run Container for affected projects
        run: pnpm exec nx affected -t container
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup build tools
        uses: ./.github/actions/setup-tools

      - name: Run Test for affected projects (PR)
        if: github.ref != 'refs/heads/main'
        run: pnpm exec nx affected -t test
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - name: Run Test for all projects (main)
        if: github.ref == 'refs/heads/main'
        run: pnpm exec nx run-many --target=test --all
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@aa494459d7c39c106cc77b166de8b4250a32bb97 # v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup build tools
        uses: ./.github/actions/setup-tools

      - name: Run Lint for affected projects
        run: pnpm exec nx affected -t lint
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  push-oci-images:
    needs:
      - build
      - test
      - lint
    if: github.event_name != 'pull_request'
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write # used to push images to `ghcr.io` if used.
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            arch: amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup build tools
        uses: ./.github/actions/setup-tools

      - name: Run Container for affected projects
        run: pnpm exec nx affected -t container
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PLATFORMS: ${{ matrix.platform }}
          INPUT_TAGS: "type=sha,prefix=,suffix=-${{ matrix.arch }}"
          INPUT_PUSH: true
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  push-multi-arch-tags:
    needs:
      - push-oci-images
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write # used to push images to `ghcr.io` if used.
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: "Setup jq"
        uses: dcarbone/install-jq-action@f0e10f46ff84f4d32178b4b76e1ef180b16f82c3 # v3.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup build tools
        uses: ./.github/actions/setup-tools

      - name: Extract image list and create multi-arch tags
        run: |
          pnpm exec nx affected -t container --graph=/tmp/nx-graph.json

          export DOCKER_CLI_EXPERIMENTAL=enabled
          SHORT_SHA=${GITHUB_SHA:0:7}
          IMAGES=$(jq -r '[.tasks.tasks[].target.project] as $task_projects | .graph.nodes | to_entries[] | select(.key as $project | $task_projects | index($project)) | .value.data.targets[].options.metadata.images[]?' /tmp/nx-graph.json)


          for IMAGE in $IMAGES; do
            # Pull per-arch images
            docker pull --platform linux/amd64 $IMAGE:$SHORT_SHA-amd64
            docker pull --platform linux/arm64 $IMAGE:$SHORT_SHA-arm64

            # Push a single multi-arch tag and update "latest"
            docker buildx imagetools create -t $IMAGE:$SHORT_SHA $IMAGE:$SHORT_SHA-amd64 $IMAGE:$SHORT_SHA-arm64
            docker buildx imagetools create -t $IMAGE:latest $IMAGE:$SHORT_SHA-amd64 $IMAGE:$SHORT_SHA-arm64
          done
